---

- name: LXD init
  block:

  - name: create lxd-server.yml
    set_fact:
      master: "{{ lookup('template', 'lxd-server.yml.j2') }}"

  - debug:
      var: master
      verbosity: 1

  - name: lxd init lxd-server.yml
    command: lxd init --preseed <
    args:
      stdin: "{{ master }}"
      creates: /var/lib/lxd/networks/lxdfan0
    when: not lxd_cluster or inventory_hostname == groups.all[0]

  - name: lxc info
    command: lxc info
    register: lxc_info_src
    run_once: true
    changed_when: false

  - name: store stdout from lxc info
    set_fact:
      lxc_info="{{ lxc_info_src.stdout | from_yaml }}"

- name: LXD cluster clients
  block:
    - debug:
        var: lxc_info.environment.certificate_fingerprint

    - name: create lxc-client.yml
      set_fact:
        slaves="{{ lookup('template', 'lxd-client.yml.j2') }}"

    # - debug:
    #     var: slaves

    - name: lxd init lxd-client.yml
      command: lxd init --preseed <
      args:
        stdin: "{{ slaves }}"
      when: inventory_hostname != groups.all[0]

    ## FIXME! there seems to be a bug with core.https_address
    ## FIXME! idempotence
    - name: lxd set core.https_address
      command: lxc config set core.https_address {{ ansible_default_ipv4.address }}:8443
  when: lxd_cluster|bool
