---
# https://discuss.linuxcontainers.org/t/lxd-on-centos-7/1250

- name: RedHat7 | lxd dependencies install
  yum:
    name: "{{ lxd_packages }}"
    state: present
    update_cache: yes
  register: pkg_result
  until: pkg_result is success

- name: RedHat7 | Enable ganto/lxc3 copr
  command: "copr enable -y ganto/lxc3"
  args:
    creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:ganto:lxc3.repo
    warn: False



- name: RedHat7 | Configure ZFS repository
  command: "{{ item }}"
  with_items:
    - yum-config-manager --disable zfs
    - yum-config-manager --enable zfs-kmod

- name: RedHat7 | Ensure ZFS is present
  yum:
    name: zfs
    state: present
    update_cache: yes
  register: pkg_result
  until: pkg_result is success

- name: RedHat7 | Configure Kernel
  command: "{{ item }}"
  with_items:
    - grubby --args="user_namespace.enable=1" --update-kernel="$(grubby --default-kernel)"
    - grubby --args="namespace.unpriv_enable=1" --update-kernel="$(grubby --default-kernel)"
  register: kernelconf

- name: RedHat7 | reboot
  command: /sbin/reboot
  async: 0
  poll: 0
  ignore_errors: true
  when: kernelconf is changed

- name: RedHat7 | Wait for system to be back online
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 300
  when: kernelconf is changed

# https://github.com/ansible/ansible/issues/39155
# https://github.com/wekan/wekan-snap/wiki/Install-snap-with-Ansible

- name: RedHat7 | Ensure lxd is present
  yum:
    name: lxd
    state: present
    update_cache: yes
  register: pkg_result
  until: pkg_result is success

- name: RedHat7 | Ensure snapd.socket is enabled and started
  service:
    name: lxd
    enabled: yes
    state: started
